version: "3.9"
services:
  s3:
    hostname: "s3"
    image: "minio/minio"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "/home/e/Desktop/temp:/data"
    command: server /data
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "miniopassword"

  libression:
    hostname: "libression"
    image: "libression:latest"
    ports:
      - "5000:5000"
    environment:
      S3_ENDPOINT_URL: "http://host.docker.internal:9000"
      S3_ACCESS_KEY_ID: "minioadmin"
      S3_SECRET: "miniopassword"
    extra_hosts:
      - "host.docker.internal:host-gateway"
